feat: add db schema
gdsc-ssu/web pull request #23
Opened 2023-02-08 05:12 UTC by JjungminLee

## Issue

Resolves #6

## Description

DB 스키마 초안 작업을 해봤습니다! 부족한 점이 많아요! 보시고 많이 피드백 해주세요 😀

## Check List

- [ ] PR 제목을 커밋 규칙에 맞게 작성
- [ ] 적절한 라벨 설정
- [ ] GitHub Projects에 연결
- [ ] 작업한 사람 모두를 Assign
- [ ] Code Review 요청
- [ ] DB Schema를 바꾼 경우, DB Schema를 바꾸는 다른 PR이 없는지 확인
- [ ] `main` 브랜치의 최신 상태를 반영하고 있는지 확인

2023-02-08 17:51 UTC, kanghyun98 requested changes
🐰 고생 많으셨어요! 이름이랑 속성들 때문에 고민 많으셨겠어요..ㅠㅠ
그리고 제 의견이랑 변경해야할 사항들 리뷰에 남겨놨습니다! 한번씩 읽어보시고 자유롭게 의견 남겨주세요:)

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +}
🥝 음 "활동 종류"를 위한 enum의 네이밍이니깐 `ActivityType` 같은건 어떤가요?

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +  updatedAt      DateTime?
🍌 `updatedAt`도 처음에는 `createdAt`이랑 같은 값을 가지고, 이후에 변경될 때마다 업데이트 되어야하니깐 `createdAt`과 마찬가지로 NOT NULL 속성을 가져야하는 것으로 알고 있어요!

그리고 매번 직접 업데이트하지 않고 편리하게 사용할 수 있도록 Prisma에서 `@updateAt` 이라는 속성을 제공해줍니다! ([공식 문서](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#updatedat))

```suggestion
  updatedAt DateTime @updatedAt
```

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +  status         String          @default("ACTIVE")
🥝 status도 네이밍을 조금 직관적이게 deleted 같은거는 어떨까요?
그러면 기존의 status라는 이름으로 했을때는 enum으로 값을 관리해야 할 것 같은데 deleted로 하면 boolean형으로 비교적 간단하고 직관적으로 관리할 수 있을 것 같아서요!

만약 기존 네이밍을 유지한다면 위에서 말씀드렸던 것처럼 enum으로 값을 관리해야할 것 같아요!

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +  Github         Github?
🍌 이 친구들 표기법이 PascalCase로 되어있는데 camelCase로 바꿔주는게 맞는 것 같아요!

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +  status         String          @default("ACTIVE")
지난번에 정했던 부분이긴 하지만 그때는 생각을 못했어가지구, 생각나서 말씀드립니다!ㅎ

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +model ActivityEnroll {
🥝 이 테이블이 매핑 테이블임을 직관적으로 이해할 수 있도록 지난번에 정했던 이름인 `ActivityMemberMapping`이 저는 괜찮다고 생각하는데,, 다른분들 의견도 궁금해요!

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +  githubId   Int       @id @default(autoincrement())
🥝 `githubId`도 그냥 `id`로 바꾸는건 어떤가요..?ㅎ

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +  activityId Int       @unique
🍎 `activityId`는 밑에 foreign key 따로 있는거 보면 잘못 적어주신 것 같아요!

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +  memberEmail      String            @db.VarChar(300)
🥝 이것도 단순 의견인데, 이미 테이블 이름으로 member인게 명시되어 있으니깐, `memberName`, `memberEmail`을 `name`, `email`로 변경하는건 어떨까요?

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +  refreshToken     String            @db.VarChar(500)
<img width="422" alt="image" src="https://user-images.githubusercontent.com/70627979/217608123-22e30c8f-5c6a-483f-9542-f1add860d161.png">
🍌 위 이미지에서는 `refresshToken`은 Nullable한 것 같은데 어느쪽이 맞는지는 잘 모르겠어요..!

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +  Github         Github?
🍎 Activity:ActivityEnroll = 1:n 인 점을 생각해보면, `ActivityEnroll[]`으로 바꿔줘야 하는 것 같아요!
(Github도 마찬가지입니다!)

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +  MemberSeasonInfo MemberSeasonInfo?
🍎 여기도 1:n 관계인 점을 고려해서 타입 변경해줘야할 것 같습니다!

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +}
🥝 `Role` 네이밍을 확장성을 고려해서 `MemberRole`이나 `MemberRoleType`으로 변경하는건 어떤가요..?ㅎ

2023-02-08 17:51 UTC, kanghyun98 commented on src/database/schema.prisma
> +}
🍌 이름이 너무 길고 오타가 있는데, `MemberPart`이나 `MemberPartType`은 어떤가요?

2023-02-10 08:49 UTC, JjungminLee commented on src/database/schema.prisma
> +}
좋아요!

2023-02-10 08:50 UTC, JjungminLee commented on src/database/schema.prisma
> +  status         String          @default("ACTIVE")
status enum으로 관리하는거 좋은 것 같습니다!

2023-02-10 08:50 UTC, JjungminLee commented on src/database/schema.prisma
> +  Github         Github?
넵 이부분 수정할게요!

2023-02-10 08:51 UTC, JjungminLee commented on src/database/schema.prisma
> +  refreshToken     String            @db.VarChar(500)
아 이거 null 아닙니다 ㅜㅜ 제가 수정해놓을게요 죄송해요..!

2023-12-29 00:47 UTC, closed without merging